### ISSUE TITLE
Supernet/KMD orderbooks not populating after two hours

### ISSUE THREAD

**Issue by 11allbits** [lukechilds/hyperdex-bugtracker#17] opened 2018-05-04 19:16 UTC
---

HyperDEX 0.0.0-testbuild.7
Electron 2.0.0
linux 4.13.0-39-generic
Locale: en-US

**Comment by lukechilds** [comment] 2018-05-07 07:20
This would be an issue with `marketmaker`, we show the order book as soon as it's available.

@artemii235 have you noticed reduce order book performance with the latest builds?

**Comment by artemii235** [comment] 2018-05-07 11:31
@lukechilds Hi, I didn't notice any difference and didn't make any changes to it. Maybe it worth to ask @jl777 about it.

**Comment by jl777** [comment] 2018-05-07 11:37
orderbook is generated locally from whatever price data is available. if the orderbook is not appearing, it would be due to bob nodes not being online, not having prices, or issues with the LP nodes

**Comment by lukechilds** [comment] 2018-05-07 11:41
Order book does appear (at least for me) but it has been noticeably slower recently. Most likely just a network issue then, rather than a bug.

**Comment by lukechilds** [comment] 2018-05-08 09:54
@jl777 @artemii235 There is definitely a performance issue that's been introduced in `marketmaker`.

From https://github.com/artemii235/SuperNET/releases

v1.0.156 and v1.0.151 block `marketmaker` for around 12 seconds every time we call `portfolio`. I've experimented and it seems to be around 1.5 seconds per currency enabled. With only 2 currencies enabled it's around 3 seconds, with 8 currencies enabled it's around 12 seconds. Sometimes can go up to 1.5mins.

Reverting to v1.0.145 resolves the problem and `portfolio` calls are returned in about 2-3ms.

That's a performance regression of about 6000x.

To clarify, we're using electrum mode for all coins.

**Comment by jl777** [comment] 2018-05-08 12:42
pushed fix

**Comment by lukechilds** [comment] 2018-05-08 12:51
@jl777 Thanks!

@artemii235 are you able to do a new build?

**Comment by artemii235** [comment] 2018-05-08 12:52
@lukechilds Sure, should be ready in 30 minutes.

**Comment by lukechilds** [comment] 2018-05-08 12:54
@artemii235 Thanks, are these builds automated btw?

If so, would it be possible to setup automated nightly builds?

**Comment by artemii235** [comment] 2018-05-08 12:57
@lukechilds build are automated, but builds are triggered by push to my repo, it shouldn't take much time to setup same for jl777/SuperNET, need to think a bit about nightly builds. I expect nightly shouldn't be published to Github releases so we need a place for them.

**Comment by lukechilds** [comment] 2018-05-08 12:59
Yeah, you could create a `marketmaker-nightly` repo and just push nightly builds there. That way you don't pollute the stable builds.

Saying that, I don't think there is much active development on `marketmaker` in jl777/SuperNET due to v2 so maybe it's not worth the effort.

**Comment by lukechilds** [comment] 2018-05-08 13:00
I just feel bad pinging you every time we need a new feature/bugfix 😆

**Comment by artemii235** [comment] 2018-05-08 13:19
@lukechilds Here is new release: https://github.com/artemii235/SuperNET/releases/tag/v1.0.160. "Ping" doesn't happen too often, so it's ok now :)

**Comment by lukechilds** [comment] 2018-05-08 13:19
@artemii235 Thanks!

**Comment by jl777** [comment] 2018-05-08 14:48
I also just fixed a bug regarding low utxo count alice requests. for some reason it seems possible for both of the utxo pairs to be the same utxo, which of course wont work.

latest version has guards against that and this would avoid the "tx inputs already spent" error -26

**Comment by lukechilds** [comment] 2018-05-09 01:59
@artemii235 ☝️ 🙏

**Comment by artemii235** [comment] 2018-05-09 06:14
@lukechilds Published: https://github.com/artemii235/SuperNET/releases/tag/v1.0.164

**Comment by sindresorhus** [comment] 2018-05-22 06:53
Closing as we're on the latest `marketmaker` now.

**Closed as completed by sindresorhus** 2018-05-22 06:53 UTC
Labels: marketmaker related
