### ISSUE TITLE
Restoring a portfolio after application update - import dialog does not allow copy/pasting of the seed

### ISSUE THREAD

**Issue by jansako** [lukechilds/hyperdex-bugtracker#18] opened 2018-05-10 18:14 UTC
After installing a newer version ( the last nightly build), I had to restore my portfolio. The dialog box where the existing seed goes does not allow copy/pasting of the seed. I had to type it in manually. 

There are tons of user complaints in BarterDEX threads where users mess up the process even with copy/paste allowed. We really should not make the user to type in their seed...

**Comment by jansako** [comment] 2018-05-10 18:17
If the public release will be able to automatically restore the portfolio after an update, then this is not such an issue. Not sure if the install is completely clearing out profile data for consistency reasons in the testing releases.

**Comment by lukechilds** [comment] 2018-05-11 02:22
>If the public release will be able to automatically restore the portfolio after an update, then this is not such an issue. Not sure if the install is completely clearing out profile data for consistency reasons in the testing releases.

HyperDEX and HyperDEX Nightly are two separate apps. We did this intentionally to avoid conflict, they don't share any settings. Updating to a new version of HyperDEX will never lose any settings.

>The dialog box where the existing seed goes does not allow copy/pasting of the seed. I had to type it in manually.

Copy/pasting is supported and working for me:

![paste](https://user-images.githubusercontent.com/2123375/39903224-5a427828-54fc-11e8-9ab4-2a526561a5df.gif)

What OS are you on?

Also, are you able to use the "Feedback" button in the app. It'll pre-fill out some help info in the GitHub Issue. Also the official repo is open now (please don't share) can you report future issues over there: https://github.com/lukechilds/hyperdex

**Comment by jansako** [comment] 2018-05-11 07:56
I am on Win10. Tried CTRL = V, tried R-click. Neither worked.

OK, will file issues in the HyperDex repo in the future.

**Comment by sindresorhus** [comment] 2018-05-22 07:06
Closing as I cannot reproduce it either. If you're still having this problem with the [latest alpha version](https://github.com/lukechilds/hyperdex/releases/tag/v0.1.0-alpha.1), could you open a new issue on https://github.com/lukechilds/hyperdex using the "Feedback" button in the app?

**Closed as completed by sindresorhus** 2018-05-22 07:06 UTC
